---
abstract: 'Display run time and dependencies after running code'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-EndStats
requires:
  perl: 5.007003
resources:
  homepage: http://search.cpan.org/dist/Devel-EndStats/
  repository: http://github.com/sharyanto/perl-Devel-EndStats
version: 0.12
